config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('home.urls')),
    path('users/',include('users.urls')),
    path('products/',include('products.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from .views import landing_page,GetTest

app_name = 'home'
urlpatterns =[
    path('',landing_page,name='landing_page'),
    path('testt/',GetTest.as_view(),name='test')
]

users/urls.py
from django.urls import path
from .views import RegisterView, LoginView, LogoutView, ProfileView, ProfileUpdateView

app_name = 'users'
urlpatterns = [
    path('register/', RegisterView.as_view(), name='register'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('profile_update/', ProfileUpdateView.as_view(), name='edit_profile'),
    
]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
# Create your models here.

class CustomUser(AbstractUser):
    image=models.ImageField(upload_to='users_images/',blank=True,null=True,default='default_images/user_image.png')
    
    class Meta:
        db_table = 'customuser'

    def __self__(self):
        return self.username

users/forms.py
from django import forms
from users.models import CustomUser

class CustomUserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = CustomUser
        fields = ('username', 'email', 'first_name', 'last_name', 'image', 'password')

    def save(self, commit=True):
        user = super().save(commit=False)  # Don't commit yet to avoid saving twice
        user.set_password(self.cleaned_data["password"])
        if commit:
            user.save()
        return user
    
class ProfilUpdateForm(forms.ModelForm):
    class Meta:
        model = CustomUser
        fields = ('username', 'email','first_name', 'last_name', 'image',)

        

users/views.py
from django.shortcuts import render,redirect
from .models import CustomUser
from django.views import View
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login,logout
from django.contrib.auth.mixins import LoginRequiredMixin
from .forms import CustomUserForm, ProfilUpdateForm
from django.contrib import messages
# Create your views here.

class RegisterView(View):
    def get(self, request):
        create_form = CustomUserForm()
        context = {
            'form': create_form
        }
        return render(request, 'register.html', context=context)

    def post(self, request):
        create_form = CustomUserForm(data=request.POST, files=request.FILES)
        if create_form.is_valid():
            create_form.save()
            messages.success(request, 'Registration successful!')             
            return redirect('users:login')
        else:
            context = {
                'form': create_form
            }
            messages.error(request,'Something is wrong! \nTry again')
            return render(request, 'register.html', context=context)


# class RegisterView(View):
#     def get(self, request):
#         return render(request, 'register.html')
#
#     def post(self, request):
#         username = request.POST['username']
#         password = request.POST['password']
#         email = request.POST['email']
#         last_name = request.POST['last_name']
#         first_name = request.POST['first_name']
#
#         user = CustomUser.objects.create_user(
#             username=username,
#             email=email,
#             first_name=first_name,
#             last_name=last_name
#         )
#         user.set_password(password)
#         user.save()
#
#         return redirect('users:login')


class LoginView(View):
    def get(self, request):
        login_form = AuthenticationForm()
        context = {
            'form': login_form
        }
        return render(request, 'login.html', context=context)

    def post(self, request):
        login_form = AuthenticationForm(data=request.POST)
        if login_form.is_valid():
            user = login_form.get_user()
            login(request, user)
            messages.success(request, 'You are now logged in') 
            return redirect('home:landing_page')
        else:
            context = {
                'form': login_form
            }
            return render(request, 'login.html', context=context)


class LogoutView(LoginRequiredMixin, View):
    def get(self, request):
        logout(request)
        messages.success(request, 'You are now logged out')
        return redirect('home:landing_page')
    
class ProfileView(LoginRequiredMixin, View):
    def get(self, request):
        return render(request, 'profile.html', {'user': request.user})
    
class ProfileUpdateView(LoginRequiredMixin, View):
    def get(self, request):
        form = ProfilUpdateForm(instance=request.user)
        return render(request, 'profile_update.html', {'form': form})
    
    def post(self, request):
        form = ProfilUpdateForm(request.POST, request.FILES, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('users:profile')
        else:
            return render(request, 'profile_update.html', {'form': form})

    def post(self, request):
        form = ProfilUpdateForm(request.POST, request.FILES, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('users:profile')
        else:
            return render(request, 'profile_update.html', {'form': form}) 

users/templates/login.html
{% extends 'base.html' %}
    {% block title %} Login page{% endblock %}

{% block content %}

    <h1>Login Page</h1>
    <form method="post">
        {% csrf_token %}
        {{form.as_p}}
        <button type="submit" >Submit</button>
    </form>


{% endblock content %}

users/templates/profil_update.html
{% extends "base.html" %}
    <title>{% block title %}Profile update{% endblock %} </title>

{% block content %}

<h1>Profile update</h1>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Update Profile">


</form>

<a href="{% url 'users:edit_profile' %}">Edit Profile</a> 

{% endblock content %}

users/templates/profile.html
{% extends "base.html" %}
    <title>{% block title %}Profile{% endblock %} </title>

{% block content %}

<h1>Profile</h1>
<img alt="user-image" style="border-radius: 50%;" src="{{ user.image.url }}" height="200"><br><br>
Username : {{ user.username }}<br>
First name : {{ user.first_name }}<br>
Last name : {{ user.last_name }}<br>
Email : {{ user.email }}<br>

<a href="{% url 'users:edit_profile' %}">Edit Profile</a>

{% endblock content %}

users/templates/register.html
{% extends 'base.html' %}   
   <title>{% block title %}Register page{% endblock %}</title>
{% block content %}
    <h1>Registe page</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" >Submit</button>
    </form>
{% endblock content %}