config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('home.urls')),
    path('users/',include('users.urls')),
    path('products/',include('products.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from .views import landing_page,GetTest

app_name = 'home'
urlpatterns =[
    path('',landing_page,name='landing_page'),
    path('testt/',GetTest.as_view(),name='test')
]

products/urls.py
from django.urls import path 
from .views import ListView, BookListView,BookDetailView,BookCreateView,BookDeleteView,AddReviewView,ReviewDeleteView,ReviewUpdateView


app_name = 'products'
urlpatterns = [
    path('books/',BookListView.as_view(),name='book_list'),
    path('deatail/<int:pk>',BookDetailView.as_view(),name='book_detail'),
    path('create/',BookCreateView.as_view(),name='book_create'),
    path('delete/<int:pk>',BookDeleteView.as_view(),name='book_delete'),
    path('add_review/<int:pk>', AddReviewView.as_view(), name='add_review'),  
    path('review_delete/<int:pk>', ReviewDeleteView.as_view(), name='review_delete'),
    path('review_update/<int:pk>', ReviewUpdateView.as_view(), name='review_update'),
]

templates/book/add_review.html
{% extends "base.html" %}
    <title>{% block title %}Add review{% endblock %} </title>

{% block content %}
    <h1>{{ books.title }}</h1>
    <form method="post" >
        {% csrf_token %}
        {{ add_review_form.as_p }}
        <input type="submit" value="Add Review">
    </form>
{% endblock content %}

templates/book/book_create.html
{% extends "base.html" %}
    <title>{% block title %}Create Book{% endblock %} </title>

{% block content %}
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Create Book</button>
</form>
{% endblock content %}

templates/book/book_detail.html
{% extends "base.html" %}
    <title>{% block title %}{{ book.title }}{% endblock %} </title>

{% block content %}
        <h1>{{ book.title }}</h1>   
    <img src="{{ book.image.url }}" alt="its">
    <h4>Description: {{book.description}}</h4>
    <h4>Price: {{book.price}}</h4>
    <h4>Page: {{book.page}}</h4> 

    
    <hr><hr>
    <h2>Reviews</h2>
    <a href="{% url 'products:add_review' book.pk %}" >Add Review</a>
    {% for review in reviews %}
        <h4>{{ review.user.username }} | {{ review.rating }}</h4>
        <p>{{ review.comment }}</p>
        {% if user.is_authenticated and review.user == user %}
        <form method="post" action="{% url 'products:review_delete' review.pk %}">
            {% csrf_token %}
            <input type="submit" value="Delete">
        </form>
        <br>
        <form method="post" action="{% url 'products:review_update' review.pk %}">
            {% csrf_token %}
            
            <input type="submit" value="Update">
        </form>
        {% endif %}
        <hr>
    {% endfor %}
{% endblock content %}

templates/book/book_list.html
{% extends "base.html" %}
    <title>{% block title %} Books {% endblock %} </title>

{% block content %}
<h1>Book Page</h1>
{% for b in books %}
    <a href="{% url  'products:book_detail' b.pk %}"> {{ b.title}}</a><br><br>
{% endfor %}
<button> 
    <a href="{% url 'products:book_create' %}">Create Book</a>
</button>
{% endblock content %}

templates/book/update_review.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Update Review</title>
</head>
<body>
<h1>Update Review</h1>
<form method="post">
    {% csrf_token %}   
    {{ form.as_p }}
    <input type="submit" value="Update Review">
</form>
</body>
</html>