config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('home.urls')),
    path('users/',include('users.urls')),
    path('products/',include('products.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from .views import landing_page,GetTest

app_name = 'home'
urlpatterns =[
    path('',landing_page,name='landing_page'),
    path('testt/',GetTest.as_view(),name='test')
]

products/urls.py
from django.urls import path 
from .views import ListView, BookListView,BookDetailView,BookCreateView,BookDeleteView,AddReviewView,ReviewDeleteView,ReviewUpdateView


app_name = 'products'
urlpatterns = [
    path('books/',BookListView.as_view(),name='book_list'),
    path('deatail/<int:pk>',BookDetailView.as_view(),name='book_detail'),
    path('create/',BookCreateView.as_view(),name='book_create'),
    path('delete/<int:pk>',BookDeleteView.as_view(),name='book_delete'),
    path('add_review/<int:pk>', AddReviewView.as_view(), name='add_review'),  
    path('review_delete/<int:pk>', ReviewDeleteView.as_view(), name='review_delete'),
    path('review_update/<int:pk>', ReviewUpdateView.as_view(), name='review_update'),
]

users/urls.py
from django.urls import path
from .views import RegisterView, LoginView, LogoutView, ProfileView, ProfileUpdateView

app_name = 'users'
urlpatterns = [
    path('register/', RegisterView.as_view(), name='register'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('profile_update/', ProfileUpdateView.as_view(), name='edit_profile'),
    
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}  {% endblock %}</title>
</head>
<body>
    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>
            {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}Important: {% endif %}
            {{ message }}
        </li>
        {% endfor %}
    </ul>
    <hr>
    {% endif %}
    
    <a href="{% url 'home:landing_page' %}">Home</a> /
    <a href="{% url 'products:book_list' %}">Books</a> /
    <a href="{% url 'users:register' %}">Register</a> /
    <!-- <a href="{% url 'home:test' %}">Test</a> / -->
    {% if request.user.is_authenticated %}
        <a href="{% url 'users:logout' %}">Logout</a>
        <a href="{% url 'users:profile' %}">Profile</a>
    {% else %}
        <a href="{% url 'users:login' %}">Login</a>
    {% endif %}
    {% block content %} {% endblock content %}
</body>
</html>

templates/get_text.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    
</body>
</html>

templates/landing_page.html
{% extends "base.html" %}
    <title>{% block title %}Home page {% endblock %} </title>

{% block content %}
    <h1>Home page</h1>
{% endblock content %}